ger_cmbb_article:
    path: /article/{alias}
    defaults: { _controller: ger.cmbb.viewer:handle, alias: "index" }
ger_cmbb_article_search_user:
    path: /article/search/{param}
    defaults: { _controller: ger.cmbb.viewer:handle, alias: "search" }
    requirements:
        param: \d+
ger_cmbb_article_edit:
    path: /article_edit/{article_id}
    defaults: { _controller: ger.cmbb.editor:handle, article_id: "0" }
ger_cmbb_save:
    path: /save/{article_id}
    defaults: { _controller: ger.cmbb.save:handle, article_id: "0" }
ger_cmbb_folders:
    path: /folders/{user_id}
    defaults: { _controller: ger.cmbb.folders:handle, user_id: 0 }
    requirements:
        param: \d+
ger_cmbb_upload:
    path: /upload
    defaults: { _controller: ger.cmbb.upload:handle }
